package com.ssam.core.authentication;

public enum PermissionType {
	NONE,CREATEUSER,GETUSERLIST,GETUSER,UPDATEUSER,
	DELETEUSER,CREATEGROUP,DELETEGROUP,GETGROUPLIST,GETGROUP,
	UPDATEGROUP,GETPERMISSIONBYUSER;
}
